//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// FourMat.rc에서 사용되고 있습니다.
//
#define IDR_MAINFRAME                   2
#define IDR_DRAWCLTYPE                  3
#define IDR_DRAWCLTYPE_CNTR_IP          6
#define IDP_BUSY                        100
#define IDP_OLE_INIT_FAILED             101
#define IDD_PROP_RECT                   101
#define IDP_FAILED_TO_CREATE            102
#define IDC_WEIGHT                      102
#define IDC_PENCIL                      102
#define IDC_NOFILL                      103
#define ID_POPUP_MENU                   103
#define IDC_SPIN1                       104
#define IDD_SUMM_PAGE                   104
#define IDC_AUTHOR                      105
#define IDD_STAT_PAGE                   105
#define IDC_KEYWORDS                    106
#define IDC_COMMENTS                    107
#define IDC_TITLE                       108
#define IDC_SUBJECT                     109
#define IDC_TEMPLATE                    110
#define IDB_RIBBON_MAIN                 110
#define IDC_SAVEDBY                     111
#define IDC_REVNUM                      112
#define IDB_RIBBON_FILELARGE            112
#define IDC_EDITTIME                    113
#define IDB_RIBBON_FILESMALL            113
#define IDC_LASTPRINT                   114
#define IDC_CREATEDATE                  115
#define IDC_LASTSAVE                    116
#define IDR_THEME_MENU                  116
#define IDC_NUMPAGES                    117
#define IDB_RIBBON_ICONS                117
#define IDC_NUMWORDS                    118
#define IDR_WINDOWS_MENU                118
#define IDC_NUMCHARS                    119
#define IDR_POPUP_MDITABS               119
#define IDC_APPNAME                     120
#define IDR_POPUP_DROP_MDITABS          120
#define IDC_SECURITY                    122
#define IDC_THUMBNAIL                   123
#define IDR_PROPERTY                    123
#define IDR_PROPERTIES                  123
#define IDC_EDIT_FILENAME               124
#define IDC_EDIT_FILELOCATION           125
#define IDB_RIBBON_HOMELARGE            126
#define IDC_BUTTON_START                126
#define IDB_RIBBON_HOMESMALL            127
#define IDC_BUTTON_STOP                 127
#define IDB_RIBBON_VIEWSMALL            128
#define IDC_CHECK1                      128
#define IDB_RIBBON_VIEWLARGE            129
#define IDC_LIST_RESULT                 129
#define IDB_STATUSBAR_1                 130
#define IDC_BUTTON_SINGLE               130
#define IDB_STATUSBAR_2                 131
#define IDC_LIST1                       131
#define IDC_LIST_HISTORY                131
#define IDB_RIBBON_FORMATLARGE          132
#define IDC_BUTTON1                     132
#define IDB_RIBBON_FORMATSMALL          133
#define IDC_BUTTON_LEFT                 133
#define IDB_LINEWEIGHT                  134
#define IDD_LINEWEIGHT                  135
#define IDB_STYLES                      136
#define IDD_DIALOG1                     137
#define IDD_SEARCH_FORM                 137
#define IDC_SLIDER1                     137
#define IDC_NEW_SX                      138
#define IDC_SLIDER3                     138
#define IDB_BITMAP1                     139
#define IDB_LIST                        139
#define IDC_EDIT2                       139
#define IDC_NEW_SY                      139
#define IDC_ROTATE90                    139
#define IDC_NEW_HEIGHT                  139
#define IDC_CONTRAST_EDIT               139
#define IDD_HISTORY_FORM                140
#define IDC_ROTATE180                   140
#define IDC_ROTATE270                   141
#define IDB_BITMAP2                     142
#define IDC_ROTATE_USER                 142
#define IDC_ANGLE                       143
#define IDD_MultiImage                  145
#define IDC_SLIDER4                     145
#define IDC_EDIT4                       145
#define IDC_DIFFUSION_K                 145
#define IDC_CONTRAST_SLIDER             145
#define IDD_HISTORY_COMPARE             145
#define IDC_HIGH_THRESHOLD              145
#define IDD_AFFINETRANSFORM_TRANSLATION 147
#define IDC_SPIN_HEIGHT                 147
#define IDC_INTERPOLATION               148
#define IDD_AFFINETRANSFORM_ROTATION    149
#define IDC_OLD_WIDTH                   149
#define IDC_OLD_HEIGHT                  150
#define IDC_NEW_WIDTH                   151
#define IDD_FILTERING_BRIGHTNESS        152
#define IDC_SPIN_WIDTH                  152
#define IDC_ASPECT_RATIO                153
#define IDD_FILTERING_GRAY              154
#define IDC_BUTTON_MULTI                154
#define IDD_FILTERING_GAMMA             154
#define IDC_DIFFUSION_LAMBDA            155
#define IDC_DIFFUSION_ITER              156
#define IDC_NOISE_RADIO1                157
#define IDD_HISTOGRAM                   158
#define IDC_NOISE_AMOUNT                159
#define IDC_SPIN_AMOUNT                 160
#define IDC_SIGMA_EDIT                  161
#define IDD_DIALOG2                     162
#define IDD_FEATUREEXTRACTION_BLUR      162
#define IDC_SIGMA_SLIDER                162
#define IDC_BRIGHT_EDIT                 163
#define IDD_AFFINETRANSFORM_SCALING     164
#define IDC_HISTOGRAM_SLIDER            164
#define IDC_HISTOGRAM_EDIT              165
#define IDC_RESULTPICTURE               166
#define IDD_FEATUREEXTRACTION_REDUCENOISE 167
#define IDC_BUTTON_COMPARE              167
#define IDC_NOISE_RADIO2                168
#define IDD_FEATUREEXTRACTION_ADDNOISE  169
#define IDC_COMPARE_EDIT                169
#define IDC_GAMMA_SLIDER                170
#define IDC_GAMMA_EDIT                  171
#define IDD_FEATUREEXTRACTION_CANNY_EDGE 171
#define IDC_RADIO1                      172
#define IDC_CANNY_SIGMA                 174
#define IDC_LOW_THRESHOLD               175
#define IDD_FEATUREEXTRACTION_HARRIS_CORNER 175
#define IDC_HARRIS_THRESHOLD            176
#define IDC_COMPARE_SLIDER              177
#define IDD_HISTORY_ALBUM               178
#define IDC_BUTTON_RIGHT                179
#define IDC_BUTTON_ALBUM                180
#define IDC_PREVIEW                     181
#define IDC_STATIC_INCLUDESTR           182
#define IDC_STATIC_LOCATION             183
#define IDD_ABOUTBOX                    999
#define ID_CANCEL_EDIT                  32768
#define ID_VIEW_GRID                    32769
#define ID_DRAW_SELECT                  32770
#define ID_DRAW_LINE                    32771
#define ID_DRAW_RECT                    32772
#define ID_DRAW_ROUNDRECT               32773
#define ID_DRAW_ELLIPSE                 32774
#define ID_OBJECT_LINECOLOR             32775
#define ID_OBJECT_FILLCOLOR             32776
#define ID_OBJECT_MOVETOFRONT           32777
#define ID_OBJECT_MOVETOBACK            32778
#define ID_OBJECT_MOVEFORWARD           32779
#define ID_OBJECT_MOVEBACK              32780
#define ID_VIEW_PAPERCOLOR              32781
#define ID_DRAW_POLYGON                 32782
#define ID_FILE_SUMMARYINFO             32792
#define ID_WINDOWS_MENU                 32793
#define ID_WINDOW_WINDOWS               32812
#define ID_WINDOW_MANAGER               32813
#define ID_VIEW_APPLOOK_2007            32818
#define ID_VIEW_APPLOOK_2007_1          32819
#define ID_VIEW_APPLOOK_2007_2          32820
#define ID_VIEW_APPLOOK_2007_3          32821
#define ID_VIEW_APPLOOK_SCENIC          32822
#define ID_NEWWINDOW                    32823
#define ID_MDI_NEW_HORZ_TAB_GROUP       32824
#define ID_MDI_NEW_VERT_GROUP           32825
#define ID_MDI_MOVE_TO_NEXT_GROUP       32826
#define ID_MDI_MOVE_TO_PREV_GROUP       32827
#define ID_MDI_CANCEL                   32828
#define ID_EXPAND                       32829
#define ID_SORTINGGROUP                 32830
#define ID_STATUSBAR_PANE_OBJECTCOUNT   32831
#define ID_STATUSBAR_PANE_SELECTEDOBJECTCOUNT 32832
#define ID_TOOLS_OPTIONS                32833
#define ID_OBJECT_NOFILL                32834
#define ID_OBJECT_LINEWEIGHT            32835
#define ID_OBJECT_LINEWEIGHT_MORE       32836
#define ID_OBJECT_PROPERTIES            32838
#define ID_OBJECT_NOLINE                32839
#define ID_OBJECT_STYLES                32840
#define ID_MULTIWINDOW                  32841
#define ID_MULTIWINDOW32842             32842
#define ID_MULTIVIEW_DOUBLEVIEW         32843
#define ID_MULTIVIEW_TRIPLEVIEW         32844
#define ID_MULTIVIEW_AFFINE             32845
#define ID_IMAGEPROCESSING_AFFINE       32846
#define ID_IMAGEPROCESSING_FILTERING    32847
#define ID_AFFINETRANFORM_ROTATION      32849
#define ID_AFFINETRANFORM_TRANSLATION   32850
#define ID_AFFINETRANFORM_SLICE         32851
#define ID_AFFINETRANFORM_SCALING       32852
#define ID_AFFINETRANFORM_SLICE32853    32853
#define ID_FILTERING_REMOVENOISE        32854
#define ID_FILTERING_BRIGHTNESS         32855
#define ID_FILTERING_CONTRAST           32856
#define ID_AFFINETRANSFORM_ROTATION     32858
#define ID_AFFINETRANSFORM_SLICE        32860
#define ID_AFFINETRANSFORM_SCALING      32861
#define ID_FILTERING_REMOVENOISE32862   32862
#define ID_FILTERING_BRIGHTNESS32863    32863
#define ID_FILTERING_CONTRAST32864      32864
#define ID_FILTERING_HISTOGRAM          32865
#define ID_FILTERING_TOGRAYSCALE        32866
#define ID_AFFINETRANSFORM_TRANSLATION  32867
#define ID_AFFINETRANFORM_MIRROR        32869
#define ID_AFFINETRANSFORM_FLIP         32870
#define ID_IMAGEPROCESSING_FEATUREEXTRACTION 32871
#define ID_FEATUREEXTRACTION_BLUR       32872
#define ID_FEATUREEXTRACTION_SHARPENING 32873
#define ID_FEATUREEXTRACTION_ADDNOISE   32874
#define ID_FEATUREEXTRACTION_REDUCENOISE 32875
#define ID_FILTERING_WINDOWLEVEL        32876
#define ID_FILTERING_INVERSE            32877
#define ID_FEATUREEXTRACTION_HISTOGRAMEQUALIZATION 32878
#define ID_FEATUREEXTRACTION_HISTOGRAMSTRETCHING 32879
#define ID_IMAGEPROCESSING_MOLPHOLOGY   32880
#define ID_MOLPHOLOGY_EROSION           32881
#define ID_MOLPHOLOGY_DILATION          32882
#define ID_MOLPHOLOGY_OPENING           32883
#define ID_MOLPHOLOGY_CLOSING           32884
#define ID_OBJECT_SAVEDRAW              32885
#define ID_FILTERING_GAMMA              32886
#define ID_FEATUREEXTRACTION_CANNYEDGE  32887
#define ID_FEATUREEXTRACTION_HARRISCOR  32888
#define ID_FEATUREEXTRACTION_HARRISCORNER 32889
#define ID_IMAGEPROCESSING_COMPARE      32890
#define ID_COMPARE_COMPARE              32891
#define ID_OBJECT_RESETDRAW             32892
#define ID_DRAW_LENGTH                  32893
#define ID_ACCELERATOR32896             32894

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        180
#define _APS_NEXT_COMMAND_VALUE         32895
#define _APS_NEXT_CONTROL_VALUE         184
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
